src/Entity/Session.php
<?php
//
// Entité "Session", fournissant la classe de base ainsi que ses getters/setters des attributs privés de la classe.
//
// Quelques méthodes personnalisées sont ajoutées en fin de fichier.
//

namespace App\Entity;

use DateTime;
use App\Entity\Programme;
use App\Entity\Stagiaire;
use Doctrine\ORM\Mapping as ORM;
use Doctrine\Common\Collections\Collection;
use Doctrine\Common\Collections\ArrayCollection;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity(repositoryClass="App\Repository\SessionRepository")
 */
class Session
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=127)
     */
    private $intitule;

    /**
     * @ORM\Column(type="date")
     */
    private $dateDebut;

    /**
     * @ORM\Column(type="date")
     */
    private $dateFin;

    /**
     * @ORM\Column(type="integer")
     */
    private $nbPlaces;

    private $nbPlacesRestantes;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Programme", mappedBy="session", cascade={"persist"}, orphanRemoval=true)
     * @ORM\OrderBy({"module" = "ASC"})
     */
    private $programmes;

    /**
     * @ORM\ManyToMany(targetEntity="App\Entity\Stagiaire", inversedBy="sessions")
     * @ORM\OrderBy({"nom" = "ASC", "prenom" = "ASC"})
     */
    private $stagiaires;

    public function __construct()
    {
        $this->programmes = new ArrayCollection();
        $this->stagiaires = new ArrayCollection();
        $this->nbPlacesRestantes = $this->nbPlaces;
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getIntitule(): ?string
    {
        return $this->intitule;
    }

    public function setIntitule(string $intitule): self
    {
        $this->intitule = $intitule;

        return $this;
    }

    public function getDateDebut(): ?\DateTimeInterface
    {
        return $this->dateDebut;
    }

    public function setDateDebut(\DateTimeInterface $dateDebut): self
    {
        $this->dateDebut = $dateDebut;

        return $this;
    }

    public function getDateFin(): ?\DateTimeInterface
    {
        return $this->dateFin;
    }

    public function setDateFin(\DateTimeInterface $dateFin): self
    {
        $this->dateFin = $dateFin;

        return $this;
    }

    public function getNbPlaces(): ?int
    {
        return $this->nbPlaces;
    }

    public function setNbPlaces(int $nbPlaces): self
    {
        $this->nbPlaces = $nbPlaces;

        return $this;
    }

    public function getNbPlacesRestantes(): ?int
    {
        return $this->nbPlacesRestantes;
    }

    public function setNbPlacesRestantes($nbPlacesRestantes): self
    {
        $this->nbPlacesRestantes = $nbPlacesRestantes;

        return $this;
    }

    /**
     * @return Collection|Programme[]
     */
    public function getProgrammes(): Collection
    {
        return $this->programmes;
    }

    public function addProgramme(Programme $programme): self
    {
        if (!$this->programmes->contains($programme)) {
            $this->programmes[] = $programme;
            $programme->setSession($this);
        }

        return $this;
    }

    public function removeProgramme(Programme $programme): self
    {
        if ($this->programmes->contains($programme)) {
            $this->programmes->removeElement($programme);
            // set the owning side to null (unless already changed)
            if ($programme->getSession() === $this) {
                $programme->setSession(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|Stagiaire[]
     */
    public function getStagiaires(): Collection
    {
        return $this->stagiaires;
    }

    public function addStagiaire(Stagiaire $stagiaire): self
    {
        if (!$this->stagiaires->contains($stagiaire)) {
            $this->stagiaires[] = $stagiaire;
            $this->nbPlacesRestantes--;
        }

        return $this;
    }

    public function removeStagiaire(Stagiaire $stagiaire): self
    {
        if ($this->stagiaires->contains($stagiaire)) {
            $this->stagiaires->removeElement($stagiaire);
            $this->nbPlacesRestantes++;
        }

        return $this;
    }

    //
    // Méthodes personnalisées
    //

    public function __toString(): string
    {
        return $this->intitule;
    }

    public function getDuree(): ?int
    {
        $duree = 0 ;
        foreach ($this->programmes as $programme) {
            $duree += $programme->getDuree() ;
        }
        return $duree;
    }

    public function getNbJoursOuvres(): ?int
    {
        $duree = 0 ;

        $jrD = $this->getDateDebut()->format("z") ;
        $jrF = $this->getDateFin()->format("z") ;

        $anD = $this->getDateDebut()->format("Y") ;
        $anF = $this->getDateFin()->format("Y") ;

        $an = $anD ;
        // Pour chaque année couverte par la session de formation ...
        do {
            // Quantième de la date de Pâques de l'année en cours (permettra de trouver les jours fériés mobiles)
            $noJP = easter_days($an) + date("z", mktime(0, 0, 0, 31, 3, $an));

            // Quantièmes du premier jour et du dernier jour à prendre en compte dans l'année en cours 
            $noJD = ($an == $anD) ? $jrD : 0 ;
            $noJF = ($an == $anF) ? $jrF : date("z", mktime(0, 0, 0, 31, 12, $an)) ;

            // Construction d'un tableau des jours fériés (en Alsace !)
            $tblF = array(
                // Dates fixes
                date("z", mktime(0, 0, 0, 1, 1, $an)),      // Jour de l'An
                date("z", mktime(0, 0, 0, 5, 1, $an)),      // Fête du travail
                date("z", mktime(0, 0, 0, 5, 8, $an)),      // Victoire 1945
                date("z", mktime(0, 0, 0, 7, 14, $an)),     // Fête Nationale
                date("z", mktime(0, 0, 0, 8, 15, $an)),     // Assomption
                date("z", mktime(0, 0, 0, 11, 1, $an)),     // Toussaint
                date("z", mktime(0, 0, 0, 11, 11, $an)),    // Victoire 1918
                date("z", mktime(0, 0, 0, 12, 25, $an)),    // Noël
                date("z", mktime(0, 0, 0, 12, 26, $an)),    // Lendemain de Noël
                // Fêtes mobiles (basées sur la date de Pâques)
                $noJP - 2,                                  // Vendredi Saint
                $noJP + 1,                                  // Lundi de Pâques
                $noJP + 39,                                 // Jeudi de l'Ascension
                $noJP + 50,                                 // Lundi de Pentecôte
            ) ;

            // Pour tous les jours de l'année en cours, situés entre les jours de début et de fin ...
            for ($j = $noJD ; $j <= $noJF ; $j++) {
                $typJ = date("w", (mktime(0, 0, 0, 1, 1, $an) + ($j * (24 * 60 * 60)))) ;

                // ... on ne compte '+ 1' que si le jour n'est ni un dimanche, ni un samedi, ni un jour férié.
                $duree += ((($typJ == 0) || ($typJ == 6)) || in_array($j, $tblF)) ? 0 : 1 ;
            }

            $an++ ;
        } while ($an < $anF) ;

        return $duree;
    }

    public function getNbStagiaires(): ?int
    {
        return count($this->stagiaires);
    }

    public function getNbPlacesLibres(): ?int
    {
        $this->setNbPlacesRestantes($this->getNbPlaces() - $this->getNbStagiaires());
        return $this->getNbPlacesRestantes() ;
    }

    public function getNbModules(): ?int
    {
        return count($this->programmes);
    }

    public function getFuture(): ?bool 
    {
        $now = new DateTime("NOW") ;

        return ($now < $this->getDateDebut());
    }

    public function getVerrou(): ?bool 
    {
        $now = new DateTime("NOW") ;

        return (($now >= $this->getDateDebut()) || ($this->getNbStagiaires() > 0));
    }
}

src/Entity/Stagiaire.php
<?php
//
// Entité "Stagiaire", fournissant la classe de base ainsi que ses getters/setters des attributs privés de la classe.
//
// Quelques méthodes personnalisées sont ajoutées en fin de fichier.
//

namespace App\Entity;

use DateTime;
use Doctrine\ORM\Mapping as ORM;
use Doctrine\Common\Collections\Collection;
use Doctrine\Common\Collections\ArrayCollection;

/**
 * @ORM\Entity(repositoryClass="App\Repository\StagiaireRepository")
 */
class Stagiaire
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=63)
     */
    private $nom;

    /**
     * @ORM\Column(type="string", length=63)
     */
    private $prenom;

    /**
     * @ORM\Column(type="string", length=7)
     */
    private $sexe;

    /**
     * @ORM\Column(type="date")
     */
    private $dateNaissance;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $adresse;

    /**
     * @ORM\Column(type="string", length=15, nullable=true)
     */
    private $cpostal;

    /**
     * @ORM\Column(type="string", length=63, nullable=true)
     */
    private $ville;

    /**
     * @ORM\Column(type="string", length=23, nullable=true)
     */
    private $telephone;

    /**
     * @ORM\Column(type="string", length=255, unique=true)
     */
    private $mail;

    /**
     * @ORM\ManyToMany(targetEntity="App\Entity\Session", mappedBy="stagiaires")
     * @ORM\OrderBy({"dateDebut" = "ASC", "dateFin" = "ASC"})
     */
    private $sessions;

    public function __construct()
    {
        $this->sessions = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNom(): ?string
    {
        return (mb_strtoupper($this->nom));
    }

    public function setNom(string $nom): self
    {
        $this->nom = $nom;

        return $this;
    }

    public function getPrenom(): ?string
    {
        return ucwords($this->prenom, "-_ \t\r\n\f\v");
    }

    public function setPrenom(string $prenom): self
    {
        $this->prenom = $prenom;

        return $this;
    }

    public function getSexe(): ?string
    {
        return $this->sexe;
    }

    public function setSexe(string $sexe): self
    {
        $this->sexe = $sexe;

        return $this;
    }

    public function getDateNaissance(): ?\DateTimeInterface
    {
        return $this->dateNaissance;
    }

    public function setDateNaissance(\DateTimeInterface $dateNaissance): self
    {
        $this->dateNaissance = $dateNaissance;

        return $this;
    }

    public function getAdresse(): ?string
    {
        return $this->adresse;
    }

    public function setAdresse(?string $adresse): self
    {
        $this->adresse = $adresse;

        return $this;
    }

    public function getCpostal(): ?string
    {
        return $this->cpostal;
    }

    public function setCpostal(?string $cpostal): self
    {
        $this->cpostal = $cpostal;

        return $this;
    }

    public function getVille(): ?string
    {
        return $this->ville;
    }

    public function setVille(?string $ville): self
    {
        $this->ville = $ville;

        return $this;
    }

    public function getTelephone(): ?string
    {
        return $this->telephone;
    }

    public function setTelephone(?string $telephone): self
    {
        $this->telephone = $telephone;

        return $this;
    }

    public function getMail(): ?string
    {
        return $this->mail;
    }

    public function setMail(string $mail): self
    {
        $this->mail = $mail;

        return $this;
    }

    /**
     * @return Collection|Session[]
     */
    public function getSessions(): Collection
    {
        return $this->sessions;
    }

    public function addSession(Session $session): self
    {
        if (!$this->sessions->contains($session)) {
            $this->sessions[] = $session;
            $session->addStagiaire($this);
        }

        return $this;
    }

    public function removeSession(Session $session): self
    {
        if ($this->sessions->contains($session)) {
            $this->sessions->removeElement($session);
            $session->removeStagiaire($this);
        }

        return $this;
    }
    
    //
    // Méthodes personnalisées
    //

    public function __toString(): string
    {
        return $this->getNomPrenom();
    }

    public function getNomPrenom(): ?string
    {
        return ($this->getNom().' '.$this->getPrenom());
    }
    public function getAge(): ?int
    {
        $now = new DateTime("NOW") ;
        return $now->diff($this->dateNaissance)->y ;
    }

    public function getNbSessionsSuivies(): ?int
    {
        return count($this->sessions) ;
    }

    public function getNbSessionsFutures(): ?int
    {
        $now = new DateTime("NOW") ;
        $nbsess = 0 ;
        foreach ($this->sessions as $session) {
            $nbsess += ($now < $session->getDateDebut()) ? 1 : 0 ;
        }
        return $nbsess ;
    }

    public function getNbSessionsEnCours(): ?int
    {
        $now = new DateTime("NOW") ;
        $nbsess = 0 ;
        foreach ($this->sessions as $session) {
            $nbsess += (($now >= $session->getDateDebut()) && ($now <= $session->getDateFin())) ? 1 : 0 ;
        }
        return $nbsess ;
    }

    public function getNbSessionsAchevees(): ?int
    {
        $now = new DateTime("NOW") ;
        $nbsess = 0 ;
        foreach ($this->sessions as $session) {
            $nbsess += ($now > $session->getDateFin()) ? 1 : 0 ;
        }
        return $nbsess ;
    }
}

templates/stagiaire/ajax.html.twig
{% if (stagiaire.nbSessionsSuivies == 0) or ((stagiaire.nbSessionsEnCours + stagiaire.nbSessionsFutures) == 0) %}
<table>
    <tbody>
        <tr>
            <td class="center">
                &nbsp;
            </td>
            <th>{{stagiaire.nom | upper}} {{stagiaire.prenom | title}}</th>
        </tr>
       <tr>
            <th class="right">Né{% if stagiaire.sexe == 'F' %}e{% endif %} le</th>
            <td>{{stagiaire.dateNaissance | date("d/m/Y")}} ({{stagiaire.age}} ans)</td>
        </tr>
        <tr>
            <th class="right">Adresse</th>
            <td>{{stagiaire.adresse}}<br>{{stagiaire.cPostal}}&nbsp;{{stagiaire.ville | upper}}</td>
        </tr>
       <tr>
            <th class="right">Téléphone</th>
            <td>{{stagiaire.telephone}}</td>
        </tr>
        <tr>
            <th class="right">Mail</th>
            <td>{{stagiaire.mail}}</td>
        </tr>
    </tbody>
</table>
{% else %}
<span class="badge badge-danger">Stagiaire non supprimable !</span>
{% endif %}

templates/stagiaire/detail.html.twig
{# Vue associée à l'affichage des détails d'un stagiaire (y compris les sessions auxquelles il participe, et intégrant un mini-formulaire local d'inscription) #}

{% extends 'base.html.twig' %}

{% block body %}
    <h1 class="center">Fiche stagiaire</h1>
    <table>
        <tbody>
            <tr>
                <td class="center">
                    {% if is_granted('ROLE_ADMIN') %}
                    <a class="button" href="{{path('update_stagiaire', {'id': stagiaire.id})}}"><i class="fas fa-pencil-alt"></i></a>
                    {% endif %}
                </td>
                <th>{{stagiaire.nom | upper}} {{stagiaire.prenom | title}}</th>
            </tr>
           <tr>
                <th class="right">Né{% if stagiaire.sexe == 'F' %}e{% endif %} le</th>
                <td>{{stagiaire.dateNaissance | date("d/m/Y")}} ({{stagiaire.age}} ans)</td>
            </tr>
            <tr>
                <th class="right">Adresse</th>
                <td>{{stagiaire.adresse}}<br>{{stagiaire.cPostal}}&nbsp;{{stagiaire.ville | upper}}</td>
            </tr>
           <tr>
                <th class="right">Téléphone</th>
                <td>{{stagiaire.telephone}}</td>
            </tr>
            <tr>
                <th class="right">Mail</th>
                <td>{{stagiaire.mail}}</td>
            </tr>
        </tbody>
    </table>

    {% if stagiaire.nbSessionsSuivies > 0 %}
    <table>
        <thead>
            <tr>
                {% if is_granted('ROLE_ADMIN') %}
                <th colspan="4" class="center">Sessions suivies</th>
                {% else %}
                <th colspan="3" class="center">Sessions suivies</th>
                {% endif %}
            </tr>
            <tr>
                <th class="left">Intitulé</th>
                <th class="left">Dates</th>
                <th class="center">Nb. jours</th>
                {% if is_granted('ROLE_ADMIN') %}
                <th class="center">Action</th>
                {% endif %}
            </tr>
        </thead>
        <tbody>
            {% for session in stagiaire.sessions %}
            <tr>
                <td class="left">{{session.intitule}}</td>
                <td class="left">du {{session.dateDebut | date("d/m/Y")}} au {{session.dateFin | date("d/m/Y")}}</td>
                <td class="center">{{session.duree}}</td>
                {% if is_granted('ROLE_ADMIN') %}
                <td class="center">
                    {% if session.future %}
                    <a class="button" href="{{ path('cancel_stagiaire', {'id': stagiaire.id, 'sessionId': session.id})}}"><i class="fas fa-trash-alt"></i></a>
                    {% else %}
                    <i class="fas fa-ban"></i>
                    {% endif %}
                </td>
                {% endif %}
            </tr>
            {% endfor %}
        </tbody>
    </table>
    {% else %}
    <div class="alert alert-info center" role="alert">Ce stagiaire n'est inscrit à aucune session...</div>
    {% endif %}

    {% if is_granted('ROLE_ADMIN') %}
        {# À défaut d'arriver à faire au préalable une requête qui ne retourne que les sessions avec des places disponibles... #}
        {% set nbDispo = 0 %}
        {% for session in sessions %}
            {% if session.nbPlaces > session.nbStagiaires %}
                {% set nbDispo = nbDispo + 1 %}
            {% endif %}
        {% endfor %}

        {# S'il y a au moins une session future, avec une place disponible, on construit un mini-formulaire permettant de s'y inscrire #}
        {% if nbDispo > 0 %}
    <div>
        <h2 class="center">Inscription à une session</h2>
        <form name="inscription" method="post" action="{{ path('register_stagiaire', {'id': stagiaire.id})}}">
            <div class="form-group row">
                <label class="col-form-label col-sm-2 required">Session choisie :</label>
                <select class="col-sm-8" name="sessionId">
                        <option value="">-- Choisissez une session disponible --</option>
                    {% for session in sessions %}
                        {% if session.nbPlaces > session.nbStagiaires %}
                        <option value="{{session.id}}">{{session.intitule}} (du {{session.dateDebut|date("d/m/Y")}} au {{session.dateFin|date("d/m/Y")}})</option>
                        {% endif %}
                    {% endfor %}
                </select>
                <div class="col-sm-2 block"><button class="button big">Inscription</button></div>
            </div>
        </form>
    </div>
        {% else %}
    <div class="alert alert-danger center" role="alert">Aucune session disponible !</div>
        {% endif %}
    {% endif %}
{% endblock %}

templates/stagiaire/form.html.twig
{# Vue associée au formulaire de création / modification d'un stagiaire (=> ses informations personnelles) #}

{% extends 'base.html.twig' %}

{% block body %}
    <h1 class="center">{{title}} un stagiaire</h1>

    {{ form(form) }}
{% endblock %}

templates/stagiaire/home.html.twig
{# Vue associée à l'affichage de la liste des stagiaires #}

{% extends 'base.html.twig' %}

{% block body %}
    {% if is_granted('ROLE_ADMIN') %}
    <p class="right mg-top"><a class="button big" href="{{path('add_stagiaire')}}">Ajouter un stagiaire</a></p>
    {% endif %}
    <h1 class="center no-mg-top">Liste des stagiaires</h1>
    <table id="liste-stagiaires" class="with-borders sort-table">
        <thead>
            <tr>
                <th class="left">Nom</th>
                <th class="left">Prénom</th>
                <th class="center">Sexe</th>
                <th class="center">Date de<br>Naissance</th>
                <th class="center">Nb. sessions<br>achevées</th>
                <th class="center">Nb. sessions<br>en cours</th>
                <th class="center">Nb. sessions<br>à venir</th>
                {% if is_granted('ROLE_ADMIN') %}
                <th class="center no-sort">Action(s)</th>
                {% else %}
                <th class="center no-sort">Détails</th>
                {% endif %}
            </tr>
        </thead>
        <tbody>
            {% for stagiaire in stagiaires %}
            <tr>
                <td class="left">{{stagiaire.nom | upper}}</td>
                <td class="left">{{stagiaire.prenom | title}}</td>
                <td class="center">{{stagiaire.sexe}}</td>
                <td class="center" data-sort="{{stagiaire.dateNaissance | date("Y-m-d")}}">{{stagiaire.dateNaissance | date("d/m/Y")}}</td>
                <td class="center">{{stagiaire.nbSessionsAchevees}}</td>
                <td class="center">{{stagiaire.nbSessionsEnCours}}</td>
                <td class="center">{{stagiaire.nbSessionsFutures}}</td>
                <td class="center no-sort">
                    <a class="button" href="{{path('detail_stagiaire', {'id': stagiaire.id})}}"><i class="far fa-eye"></i></a>
                    {% if is_granted('ROLE_ADMIN') %}
                        {% if stagiaire.nbSessionsSuivies == 0 %}
                    <a class="button remove-stagiaire-confirm"
                       data-toggle="modal" data-target="#modalPopup" data-id="{{stagiaire.id}}" 
                       href="{{path('delete_stagiaire', {'id': stagiaire.id})}}"><i class="fas fa-trash"></i></a>
                        {% else %}
                            {% if (stagiaire.nbSessionsEnCours + stagiaire.nbSessionsFutures) == 0 %}
                    <a class="button anonymize-stagiaire-confirm"
                       data-toggle="modal" data-target="#modalPopup" data-id="{{stagiaire.id}}" 
                       href="{{path('anonymize_stagiaire', {'id': stagiaire.id})}}"><i class="fas fa-mask"></i></a>
                            {% endif %}
                        {% endif %}
                    {% endif %}
                </td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
{% endblock %}