src/Entity/Session.php
<?php
//
// Entité "Session", fournissant la classe de base ainsi que ses getters/setters des attributs privés de la classe.
//
// Quelques méthodes personnalisées sont ajoutées en fin de fichier.
//

namespace App\Entity;

use DateTime;
use App\Entity\Programme;
use App\Entity\Stagiaire;
use Doctrine\ORM\Mapping as ORM;
use Doctrine\Common\Collections\Collection;
use Doctrine\Common\Collections\ArrayCollection;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity(repositoryClass="App\Repository\SessionRepository")
 */
class Session
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=127)
     */
    private $intitule;

    /**
     * @ORM\Column(type="date")
     */
    private $dateDebut;

    /**
     * @ORM\Column(type="date")
     */
    private $dateFin;

    /**
     * @ORM\Column(type="integer")
     */
    private $nbPlaces;

    private $nbPlacesRestantes;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Programme", mappedBy="session", cascade={"persist"}, orphanRemoval=true)
     * @ORM\OrderBy({"module" = "ASC"})
     */
    private $programmes;

    /**
     * @ORM\ManyToMany(targetEntity="App\Entity\Stagiaire", inversedBy="sessions")
     * @ORM\OrderBy({"nom" = "ASC", "prenom" = "ASC"})
     */
    private $stagiaires;

    public function __construct()
    {
        $this->programmes = new ArrayCollection();
        $this->stagiaires = new ArrayCollection();
        $this->nbPlacesRestantes = $this->nbPlaces;
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getIntitule(): ?string
    {
        return $this->intitule;
    }

    public function setIntitule(string $intitule): self
    {
        $this->intitule = $intitule;

        return $this;
    }

    public function getDateDebut(): ?\DateTimeInterface
    {
        return $this->dateDebut;
    }

    public function setDateDebut(\DateTimeInterface $dateDebut): self
    {
        $this->dateDebut = $dateDebut;

        return $this;
    }

    public function getDateFin(): ?\DateTimeInterface
    {
        return $this->dateFin;
    }

    public function setDateFin(\DateTimeInterface $dateFin): self
    {
        $this->dateFin = $dateFin;

        return $this;
    }

    public function getNbPlaces(): ?int
    {
        return $this->nbPlaces;
    }

    public function setNbPlaces(int $nbPlaces): self
    {
        $this->nbPlaces = $nbPlaces;

        return $this;
    }

    public function getNbPlacesRestantes(): ?int
    {
        return $this->nbPlacesRestantes;
    }

    public function setNbPlacesRestantes($nbPlacesRestantes): self
    {
        $this->nbPlacesRestantes = $nbPlacesRestantes;

        return $this;
    }

    /**
     * @return Collection|Programme[]
     */
    public function getProgrammes(): Collection
    {
        return $this->programmes;
    }

    public function addProgramme(Programme $programme): self
    {
        if (!$this->programmes->contains($programme)) {
            $this->programmes[] = $programme;
            $programme->setSession($this);
        }

        return $this;
    }

    public function removeProgramme(Programme $programme): self
    {
        if ($this->programmes->contains($programme)) {
            $this->programmes->removeElement($programme);
            // set the owning side to null (unless already changed)
            if ($programme->getSession() === $this) {
                $programme->setSession(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|Stagiaire[]
     */
    public function getStagiaires(): Collection
    {
        return $this->stagiaires;
    }

    public function addStagiaire(Stagiaire $stagiaire): self
    {
        if (!$this->stagiaires->contains($stagiaire)) {
            $this->stagiaires[] = $stagiaire;
            $this->nbPlacesRestantes--;
        }

        return $this;
    }

    public function removeStagiaire(Stagiaire $stagiaire): self
    {
        if ($this->stagiaires->contains($stagiaire)) {
            $this->stagiaires->removeElement($stagiaire);
            $this->nbPlacesRestantes++;
        }

        return $this;
    }

    //
    // Méthodes personnalisées
    //

    public function __toString(): string
    {
        return $this->intitule;
    }

    public function getDuree(): ?int
    {
        $duree = 0 ;
        foreach ($this->programmes as $programme) {
            $duree += $programme->getDuree() ;
        }
        return $duree;
    }

    public function getNbJoursOuvres(): ?int
    {
        $duree = 0 ;

        $jrD = $this->getDateDebut()->format("z") ;
        $jrF = $this->getDateFin()->format("z") ;

        $anD = $this->getDateDebut()->format("Y") ;
        $anF = $this->getDateFin()->format("Y") ;

        $an = $anD ;
        // Pour chaque année couverte par la session de formation ...
        do {
            // Quantième de la date de Pâques de l'année en cours (permettra de trouver les jours fériés mobiles)
            $noJP = easter_days($an) + date("z", mktime(0, 0, 0, 31, 3, $an));

            // Quantièmes du premier jour et du dernier jour à prendre en compte dans l'année en cours 
            $noJD = ($an == $anD) ? $jrD : 0 ;
            $noJF = ($an == $anF) ? $jrF : date("z", mktime(0, 0, 0, 31, 12, $an)) ;

            // Construction d'un tableau des jours fériés (en Alsace !)
            $tblF = array(
                // Dates fixes
                date("z", mktime(0, 0, 0, 1, 1, $an)),      // Jour de l'An
                date("z", mktime(0, 0, 0, 5, 1, $an)),      // Fête du travail
                date("z", mktime(0, 0, 0, 5, 8, $an)),      // Victoire 1945
                date("z", mktime(0, 0, 0, 7, 14, $an)),     // Fête Nationale
                date("z", mktime(0, 0, 0, 8, 15, $an)),     // Assomption
                date("z", mktime(0, 0, 0, 11, 1, $an)),     // Toussaint
                date("z", mktime(0, 0, 0, 11, 11, $an)),    // Victoire 1918
                date("z", mktime(0, 0, 0, 12, 25, $an)),    // Noël
                date("z", mktime(0, 0, 0, 12, 26, $an)),    // Lendemain de Noël
                // Fêtes mobiles (basées sur la date de Pâques)
                $noJP - 2,                                  // Vendredi Saint
                $noJP + 1,                                  // Lundi de Pâques
                $noJP + 39,                                 // Jeudi de l'Ascension
                $noJP + 50,                                 // Lundi de Pentecôte
            ) ;

            // Pour tous les jours de l'année en cours, situés entre les jours de début et de fin ...
            for ($j = $noJD ; $j <= $noJF ; $j++) {
                $typJ = date("w", (mktime(0, 0, 0, 1, 1, $an) + ($j * (24 * 60 * 60)))) ;

                // ... on ne compte '+ 1' que si le jour n'est ni un dimanche, ni un samedi, ni un jour férié.
                $duree += ((($typJ == 0) || ($typJ == 6)) || in_array($j, $tblF)) ? 0 : 1 ;
            }

            $an++ ;
        } while ($an < $anF) ;

        return $duree;
    }

    public function getNbStagiaires(): ?int
    {
        return count($this->stagiaires);
    }

    public function getNbPlacesLibres(): ?int
    {
        $this->setNbPlacesRestantes($this->getNbPlaces() - $this->getNbStagiaires());
        return $this->getNbPlacesRestantes() ;
    }

    public function getNbModules(): ?int
    {
        return count($this->programmes);
    }

    public function getFuture(): ?bool 
    {
        $now = new DateTime("NOW") ;

        return ($now < $this->getDateDebut());
    }

    public function getVerrou(): ?bool 
    {
        $now = new DateTime("NOW") ;

        return (($now >= $this->getDateDebut()) || ($this->getNbStagiaires() > 0));
    }
}

src/Entity/Stagiaire.php
<?php
//
// Entité "Stagiaire", fournissant la classe de base ainsi que ses getters/setters des attributs privés de la classe.
//
// Quelques méthodes personnalisées sont ajoutées en fin de fichier.
//

namespace App\Entity;

use DateTime;
use Doctrine\ORM\Mapping as ORM;
use Doctrine\Common\Collections\Collection;
use Doctrine\Common\Collections\ArrayCollection;

/**
 * @ORM\Entity(repositoryClass="App\Repository\StagiaireRepository")
 */
class Stagiaire
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=63)
     */
    private $nom;

    /**
     * @ORM\Column(type="string", length=63)
     */
    private $prenom;

    /**
     * @ORM\Column(type="string", length=7)
     */
    private $sexe;

    /**
     * @ORM\Column(type="date")
     */
    private $dateNaissance;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $adresse;

    /**
     * @ORM\Column(type="string", length=15, nullable=true)
     */
    private $cpostal;

    /**
     * @ORM\Column(type="string", length=63, nullable=true)
     */
    private $ville;

    /**
     * @ORM\Column(type="string", length=23, nullable=true)
     */
    private $telephone;

    /**
     * @ORM\Column(type="string", length=255, unique=true)
     */
    private $mail;

    /**
     * @ORM\ManyToMany(targetEntity="App\Entity\Session", mappedBy="stagiaires")
     * @ORM\OrderBy({"dateDebut" = "ASC", "dateFin" = "ASC"})
     */
    private $sessions;

    public function __construct()
    {
        $this->sessions = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNom(): ?string
    {
        return (mb_strtoupper($this->nom));
    }

    public function setNom(string $nom): self
    {
        $this->nom = $nom;

        return $this;
    }

    public function getPrenom(): ?string
    {
        return ucwords($this->prenom, "-_ \t\r\n\f\v");
    }

    public function setPrenom(string $prenom): self
    {
        $this->prenom = $prenom;

        return $this;
    }

    public function getSexe(): ?string
    {
        return $this->sexe;
    }

    public function setSexe(string $sexe): self
    {
        $this->sexe = $sexe;

        return $this;
    }

    public function getDateNaissance(): ?\DateTimeInterface
    {
        return $this->dateNaissance;
    }

    public function setDateNaissance(\DateTimeInterface $dateNaissance): self
    {
        $this->dateNaissance = $dateNaissance;

        return $this;
    }

    public function getAdresse(): ?string
    {
        return $this->adresse;
    }

    public function setAdresse(?string $adresse): self
    {
        $this->adresse = $adresse;

        return $this;
    }

    public function getCpostal(): ?string
    {
        return $this->cpostal;
    }

    public function setCpostal(?string $cpostal): self
    {
        $this->cpostal = $cpostal;

        return $this;
    }

    public function getVille(): ?string
    {
        return $this->ville;
    }

    public function setVille(?string $ville): self
    {
        $this->ville = $ville;

        return $this;
    }

    public function getTelephone(): ?string
    {
        return $this->telephone;
    }

    public function setTelephone(?string $telephone): self
    {
        $this->telephone = $telephone;

        return $this;
    }

    public function getMail(): ?string
    {
        return $this->mail;
    }

    public function setMail(string $mail): self
    {
        $this->mail = $mail;

        return $this;
    }

    /**
     * @return Collection|Session[]
     */
    public function getSessions(): Collection
    {
        return $this->sessions;
    }

    public function addSession(Session $session): self
    {
        if (!$this->sessions->contains($session)) {
            $this->sessions[] = $session;
            $session->addStagiaire($this);
        }

        return $this;
    }

    public function removeSession(Session $session): self
    {
        if ($this->sessions->contains($session)) {
            $this->sessions->removeElement($session);
            $session->removeStagiaire($this);
        }

        return $this;
    }
    
    //
    // Méthodes personnalisées
    //

    public function __toString(): string
    {
        return $this->getNomPrenom();
    }

    public function getNomPrenom(): ?string
    {
        return ($this->getNom().' '.$this->getPrenom());
    }
    public function getAge(): ?int
    {
        $now = new DateTime("NOW") ;
        return $now->diff($this->dateNaissance)->y ;
    }

    public function getNbSessionsSuivies(): ?int
    {
        return count($this->sessions) ;
    }

    public function getNbSessionsFutures(): ?int
    {
        $now = new DateTime("NOW") ;
        $nbsess = 0 ;
        foreach ($this->sessions as $session) {
            $nbsess += ($now < $session->getDateDebut()) ? 1 : 0 ;
        }
        return $nbsess ;
    }

    public function getNbSessionsEnCours(): ?int
    {
        $now = new DateTime("NOW") ;
        $nbsess = 0 ;
        foreach ($this->sessions as $session) {
            $nbsess += (($now >= $session->getDateDebut()) && ($now <= $session->getDateFin())) ? 1 : 0 ;
        }
        return $nbsess ;
    }

    public function getNbSessionsAchevees(): ?int
    {
        $now = new DateTime("NOW") ;
        $nbsess = 0 ;
        foreach ($this->sessions as $session) {
            $nbsess += ($now > $session->getDateFin()) ? 1 : 0 ;
        }
        return $nbsess ;
    }
}

src/Form/SessionType.php
<?php
//
// Formulaire permettant d'ajouter / de modifier une session, ainsi que son programme (<=> ses modules avec leur durée).
//
// Ce formulaire intègre le sous-formulaire "Programme", intégré à chaque fois que nécessaire via le script jQuery "gsf.js". 
//
// Ce formulaire et tous les sous-formulaires sont validés simultanément.
//

namespace App\Form;

use DateTime;
use App\Entity\Session;
use App\Form\ProgrammeType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\DateType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\Extension\Core\Type\IntegerType;
use Symfony\Component\Form\Extension\Core\Type\CollectionType;

class SessionType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $now = new DateTime ;
        
        $builder
            ->add('intitule',       TextType::class, [
                'label' => 'Intitulé de la session'
            ])
            ->add('dateDebut',      DateType::class, [
                'label' => 'Date de démarrage',
                'widget' => 'single_text'
            ])
            ->add('dateFin',        DateType::class, [
                'label' => 'Date d\'achèvement',
                'widget' => 'single_text'
            ])
            ->add('nbPlaces',       IntegerType::class, [
                'label' => 'Nombre de places',
                'attr' => [ 'min' => '1', 'max' => '25']
            ])
            ->add('programmes',     CollectionType::class, [
                'entry_type' => ProgrammeType::class,
                'prototype' => true,
                'allow_add' => true,
                'allow_delete' => true,
                'by_reference' => false
            ])
            ->add('Enregistrer',    SubmitType::class, [
                'attr' => [ 'class' => 'button big' ]
            ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Session::class,
        ]);
    }
}

templates/session/ajax.html.twig
{# Vue associée à l'affichage des détails d'une session dans la fenêtre "popup" modale de confirmation de suppression #}

{% if session.nbStagiaires == 0 %}
<table>
    <tbody>
        <tr>
            <td class="center">
                &nbsp;
            </td>
            <th>{{session.intitule}}</th>
        </tr>
       <tr>
            <th class="right">Dates</th>
            <td>du {{session.dateDebut | date("d/m/Y")}} au {{session.dateFin | date("d/m/Y")}}</td>
        </tr>
        <tr>
            <th class="right">Durée</th>
            <td>{{session.duree}} jours</td>
        </tr>
        <tr>
            <th class="right">Nb. places</th>
            <td>{{session.nbPlaces}} participants</td>
        </tr>
    </tbody>
</table>
<table>
    <thead>
        <tr>
            <th colspan="3" class="center">Programme</th>
        </tr>
        <tr>
            <th class="left">Catégorie</th>
            <th class="left">Module</th>
            <th class="center">Nb. jours</th>
        </tr>
    </thead>
    <tbody>
        {% for programme in session.programmes %}
        <tr>
            <td class="left">{{programme.module.categorie.libelle}}</td>
            <td class="left">{{programme.module.libelle}}</td>
            <td class="center">{{programme.duree}}</td>
        </tr>
        {% endfor %}
    </tbody>
</table>
{% else %}
<span class="badge badge-danger">Session non supprimable !</span>
{% endif %}

templates/session/detail.html.twig
{# Vue associée à l'affichage des détails d'une session (y compris son programme, et les stagiaires qui y sont inscrits) #}

{% extends 'base.html.twig' %}

{% block body %}
    <h1 class="center">Détail d'une session</h1>
    <table>
        <tbody>
            <tr>
                <td class="center">
                    {% if is_granted('ROLE_FORM') and session.future %}
                    <a class="button" href="{{path('update_session', {'id': session.id})}}"><i class="fas fa-pencil-alt"></i></a>
                    {% endif %}
                </td>
                <th>{{session.intitule}}</th>
            </tr>
           <tr>
                <th class="right">Dates</th>
                <td>du {{session.dateDebut | date("d/m/Y")}} au {{session.dateFin | date("d/m/Y")}}</td>
            </tr>
            <tr>
                <th class="right">Durée</th>
                <td>{{session.duree}} jours</td>
            </tr>
            <tr>
                <th class="right">Nb. places</th>
                <td>{{session.nbPlaces}} participants</td>
            </tr>
        </tbody>
    </table>
    <table>
        <thead>
            <tr>
                {% if is_granted('ROLE_FORM') and session.future %}
                <th colspan="4" class="center">Programme</th>
                {% else %}
                <th colspan="3" class="center">Programme</th>
                {% endif %}
            </tr>
            <tr>
                <th class="left">Catégorie</th>
                <th class="left">Module</th>
                <th class="center">Nb. jours</th>
                {% if is_granted('ROLE_FORM') and session.future %}
                <th class="center">Action</th>
                {% endif %}
            </tr>
        </thead>
        <tbody>
            {% for programme in session.programmes %}
            <tr>
                <td class="left">{{programme.module.categorie.libelle}}</td>
                <td class="left">{{programme.module.libelle}}</td>
                <td class="center">{{programme.duree}}</td>
                {% if is_granted('ROLE_FORM') and session.future %}
                <td class="center"><a class="button" href="{{ path('unset_programme', {'id': session.id, 'programmeId': programme.id})}}"><i class="fas fa-trash-alt"></i></a></td>
                {% endif %}
            </tr>
            {% endfor %}
        </tbody>
    </table>
    {% if is_granted('ROLE_USER') %}
    <table>
        <thead>
            <tr>
                {% if is_granted('ROLE_FORM') and session.future %}
                <th colspan="4" class="center">Participants</th>
                {% else %}
                <th colspan="3" class="center">Participants</th>
                {% endif %}
            </tr>
            <tr>
                <th class="left">Nom &amp; prénom</th>
                <th class="center">Sexe</th>
                <th class="center">Date de Naissance</th>
                {% if is_granted('ROLE_FORM') and session.future %}
                <th class="center">Action</th>
                {% endif %}
            </tr>
        </thead>
        <tbody>
            {% for stagiaire in session.stagiaires %}
            <tr>
                <td class="left">{{stagiaire.nomPrenom}}</td>
                <td class="center">{{stagiaire.sexe}}</td>
                <td class="center">{{stagiaire.dateNaissance | date("d/m/Y")}} ({{stagiaire.age}} ans)</td>
                {% if is_granted('ROLE_FORM') and session.future %}
                <td class="center"><a class="button" href="{{ path('cancel_session', {'id': session.id, 'stagiaireId': stagiaire.id})}}"><i class="fas fa-trash-alt"></i></a></td>
                {% endif %}
            </tr>
            {% endfor %}
        </tbody>
    </table>
    {% endif %}

    {# S'il y a au moins un stagiaire disponible, on construit un mini-formulaire permettant d'ajouter des participants à cette session #}
    {% if is_granted('ROLE_FORM') %}
        {% if session.future %}
            {% if (stagiaires | length) > 0 %}
    <div>
        <h2 class="center">Ajout de participants à cette session</h2>
        <form name="participation" method="post" action="{{ path('register_session', {'id': session.id})}}">
            <div class="form-group row">
                <label class="col-form-label col-sm-2 required">Stagiaire à inscrire :</label>
                <select class="col-sm-8" name="stagiaireId">
                        <option value="">-- Choisissez un stagiaire disponible --</option>
                    {% for stagiaire in stagiaires %}
                        {# {% if session.nbPlaces > session.nbStagiaires %} #}
                        <option value="{{stagiaire.id}}">{{stagiaire.nomPrenom}} ({{stagiaire.age}} ans)</option>
                        {# {% endif %} #}
                    {% endfor %}
                </select>
                <div class="col-sm-2 block"><button class="button big">Inscription</button></div>
            </div>
        </form>
    </div>
            {% else %}
    <div class="alert alert-danger center" role="alert">Aucun stagiaire disponible !</div>
            {% endif %}
        {% else %}
    <div class="alert alert-danger center" role="alert">Cette session ne peut plus être modifiée !</div>
        {% endif %}
    {% endif %}
{% endblock %}

templates/session/form.html.twig
{# Vue associée au formulaire de création / modification d'une session (et de son programme) #}

{% extends 'base.html.twig' %}

{% block body %}
    <h1 class="center">{{title}} une session</h1>

    {{ form_start(form) }}

    {# {% if not form.vars.valid %}
    <div class="alert-danger alert center">
        {{ form_errors() }}
    </div>
    {% endif %} #}

    {{ form_row(form.intitule) }}
    {{ form_row(form.dateDebut) }}
    {{ form_row(form.dateFin) }}
    {{ form_row(form.nbPlaces) }}

    {# construit dynamiquement la liste des modules existants, à partir de la collection de programmes (cf. également "gsf.js") #}
    <h2 class="center">Programme de la session</h2>
    <div class="form-group row ">
        <div class="col-form-label col-sm-2">&nbsp;</div>
        <div id="programme-fields-list" class="col-sm-10 remove-collection-widget"
            data-prototype="{{ form_widget(form.programmes.vars.prototype)|e }}"
            data-session="{{sessionId}}"
            data-widget-tags="{{ '<p></p>'|e }}"
            data-widget-counter="{{ form.programmes|length }}">
        {% for programmeField in form.programmes %}
            <p>
                {{ form_errors(programmeField) }}
                {{ form_widget(programmeField, {'attr': {'class': 'borders'}}) }}
            </p>
        {% endfor %}
        </div>
    </div>
    <div class="form-group row flex-action">
        <button type="button" 
            class="add-another-collection-widget button"
            data-list-selector="#programme-fields-list">Ajouter un nouveau module</button>
    </div>

    {# empêche l'apparition d'une légende "programmes", si la collection est vide (en cas de création d'une nouvelle session) #}
    {% do form.programmes.setRendered %}

    {{ form_end(form) }}
    
{% endblock %}

templates/session/home.html.twig
{# Vue associée à l'affichage de la liste des sessions #}

{% extends 'base.html.twig' %}

{% block body %}
    {% if is_granted('ROLE_FORM') %}
    <p class="right mg-top"><a class="button big" href="{{path('add_session')}}">Ajouter une session</a></p>
    {% endif %}
    <h1 class="center no-mg-top">Liste des sessions</h1>
    <table id="liste-sessions" class="with-borders sort-table">
        <thead>
            <tr>
                <th class="left">Intitulé session</th>
                <th class="center">Date<br>de démarrage</th>
                <th class="center">Date<br>d'achèvement</th>
                <th class="center">Nb. jours<br>ouvrés</th>
                <th class="center">Nb. jours<br>programmés</th>
                <th class="center">Nb. Places<br>théoriques</th>
                <th class="center">Nb. Places<br>réservées</th>
                <th class="center">Nb. Places<br>disponibles</th>
                {% if is_granted('ROLE_FORM') %}
                <th class="center no-sort">Action(s)</th>
                {% else %}
                <th class="center no-sort">Détails</th>
                {% endif %}
            </tr>
        </thead>
        <tbody>
            {% for session in sessions %}
            <tr>
                <td class="left">{% if not session.future %}<i class="fas fa-lock light-blue"></i>&nbsp;{% endif %}{{session.intitule}}</td>
                <td class="center" data-sort="{{session.dateDebut | date("Y-m-d")}}">{{session.dateDebut | date("d/m/Y")}}</td>
                <td class="center" data-sort="{{session.dateFin | date("Y-m-d")}}">{{session.dateFin | date("d/m/Y")}}</td>
                <td class="center">{{session.nbJoursOuvres}}</td>
                <td class="center">{{session.duree}}</td>
                <td class="center">{{session.nbPlaces}}</td>
                <td class="center">{{session.nbStagiaires}}</td>
                <td class="center">
                    {% if session.nbPlacesLibres > 0 %}
                    {{session.nbPlacesLibres}}</td>
                    {% else %}
                    <span class="badge badge-pill light-blue-back">complète</span>
                    {% endif %}
                </td>
                <td class="center no-sort">
                    <a class="button" href="{{path('detail_session', {'id': session.id})}}"><i class="far fa-eye"></i></a>
                    {% if is_granted('ROLE_FORM') and (session.nbStagiaires == 0) %}
                    <a class="button remove-session-confirm"
                       data-toggle="modal" data-target="#modalPopup" data-id="{{session.id}}" 
                       href="{{path('delete_session', {'id': session.id})}}"><i class="fas fa-trash"></i></a>
                    {% endif %}
                </td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
{% endblock %}